apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-cache-1
  resources:
    requests:
      storage: 10Gi
